name: shortlink

# 触发工作流条件
on:
  push:
    branches: [ main ] # 当推送到 main 分支时触发
  pull_request:
    branches: [ main ] # 当有 PR 提交到 main 分支时触发

# 定义工作流任务
jobs:
  build: # 任务名称
    runs-on: ubuntu-latest # 运行环境

    steps:
      - name: Checkout repository # 检出仓库代码
        uses: actions/checkout@v3 # 使用 GitHub Actions 提供的检出仓库操作

      - name: Set up Python 3.11 # 设置 Python 3.11 环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies # 安装依赖
        run : |
          python -m pip install --upgrade pip   
          pip install -r requirements.txt
          
      - name: Check FastAPI project build
        run : |
          python run app.py
          sleep 5
          curl --fail http://127.1.1.1:5000/

